### ISSUE TITLE
why not plugin in the .vimrc?

### ISSUE THREAD

**Issue by BabyMelvin** [rubberduck203/aosp-vim#1]
Just like this:`Plug 'rubberduck203/aosp-vim'`. I'm newbie in the vim config.

**Comment by rubberduck203** [comment]
No reason really. 
When I wrote this I was a pretty new com user myself. 

What plugin tool are you using?
I would be happy to look into making this compatible. (Or happily accept a pull request that does)

**Comment by rubberduck203** [comment]
Good news! Looks like it was already compatible with both [Pathogen](https://github.com/tpope/vim-pathogen) and Vim 8 plugins!
I updated the README in 1fe0707 and 83e082c.

Thanks for reaching out.
I'm glad to know someone else found this valuable.

**Comment by rubberduck203** [comment]
Oh. You're using [vim-plug](https://github.com/junegunn/vim-plug)?
I don't use that. Have you tried this line of code you posted?

```
Plug 'rubberduck203/aosp-vim'
```

Does it work?

**Comment by BabyMelvin** [comment]
Works well. Good jobs.

**Comment by rubberduck203** [comment]
Great!
