### ISSUE TITLE
Can I copy some content?

### ISSUE THREAD

**Issue by kheaactua** [rubberduck203/aosp-vim#2]
Hey,

I created my own [aosp-vim-syntax](https://github.com/kheaactua/aosp-vim-syntax)
 vim pluggin in order to add syntax highlighting to sepolicy files and such.

I've used your repo for a year, but I wanted to modify how `bp` files were handled, and I couldn't figure out a way to undo the `ftdetect/bp` autocmd you have specifying bp files as js.
```vim
autocmd BufRead,BufNewFile *.bp set filetype=javascript
```

Do you mind if I copy your `rc` files into my repo?  I'll leave the copyright and author comments at the top of the file, and cite your work when I write a README file.

My [still private] repo is at [kheaactua/aosp-vim-syntax](https://github.com/kheaactua/aosp-vim-syntax)

**Comment by rubberduck203** [comment]
All I ask is that you adhere to the GPL-3 license.

**Comment by rubberduck203** [comment]
Sorry. I’m on my mobile and misclicked. 

It’s perfectly fine to copy my code into your project so long as it’s private. Just keep in mind that if you publish the combined work, your work also needs to be published under a GPL-3 compatible license. 

If that’s not ok, we can talk about an alternative, but being a dev tool, I would prefer my work and derivatives of it to remain under that license. 

Honestly, I’m just happy someone else found this useful. I haven’t used it in quite a while, so this was a happy surprise.

**Comment by kheaactua** [comment]
hey, yep, that license is fine.  I just didn't want to accidentally steal someone elses' work. :)

**Comment by rubberduck203** [comment]
Cool. Enjoy! Super happy this was helpful.
